apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: mywebapp
    student: hiwot-beyene-ugr3774
  annotations:
    submitted-by: hiwot-beyene-ugr3774
    author: "Hiwot Beyene - UGR/3774/13"
spec:
  containers:
  - name: nginx
    image: nginx:1.23.1
    ports:
    - containerPort: 80