apiVersion: v1
kind: Service
metadata:
  name: mywebapp
  labels:
    app: mywebapp
    student: hiwot-beyene-ugr3774
  annotations:
    submitted-by: hiwot-beyene-ugr3774
    author: "Hiwot Beyene - UGR/3774/13"
spec:
  ports:
  - port: 80
    protocol: TCP
    name: flask
  selector:
    app: mywebapp
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: mywebapp
    student: hiwot-beyene-ugr3774
  annotations:
    submitted-by: hiwot-beyene-ugr3774
    author: "Hiwot Beyene - UGR/3774/13"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebapp
      tier: frontend
  template:
    metadata:
      labels:
        app: mywebapp
        tier: frontend
        student: hiwot-beyene-ugr3774
    spec:
      containers:
      - name: mycontainer
        image: devopsjourney1/mywebapp
        ports:
        - containerPort: 80